name: yue-boilerplate-actions-workflow
on: push

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        
      - name: git clone
        run: git clone --branch master https://github.com/yue/muban.git
        
      - name: build
        shell: cmd
        run: cd muban && npm install && npm run dist && dir
        
